name: 測試定時執行 Python

on:
  schedule:
    - cron: '*/5 * * * *'  # 每5分鐘執行一次（測試用）
  workflow_dispatch:  # 加上這行，啟用手動執行



jobs:
  run-python:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 執行 Python
        run: it1.py
